---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width=20, fig.height=15)
```

```{r}
library(ggmap)
library(ggplot2)
library(tidyverse)
library(repr)
library(plyr)
library(dplyr)
library(RColorBrewer)
```

```{r}
mydf = read.csv('R_viz.csv')
map = get_stamenmap(c(left = -100, bottom = 7.5, right = -50, top = 32.5), maptype = "toner-lite",zoom = 5)

mydf = mydf %>% filter(Code == 'AL252005')
mydf1 = mydf %>% filter(Hour %% 6 == 0)
mydf2 = mydf %>% filter(Hour == 12)
```

```{r}
col = rev(brewer.pal(n=length(mydf$Wind),"RdYlBu"))
#col = append(col, tail(col, n=1))
#col = append(col, col[1], after=1)
```

```{r}
THEME = theme(
    axis.text=element_text(size=22),
    axis.title=element_text(size=28,face="bold"),
    legend.title=element_text(size=24,face="bold"),
    legend.text=element_text(size=18),
    panel.border = element_rect(colour = "black", fill=NA, size=1),
    legend.direction="horizontal",
    legend.position = c(.87,.92),
    legend.background = element_rect(fill=alpha('blue', 0)),
    legend.key.size = unit(2, "cm"),
    legend.key.height = unit(.6, "cm"),
    legend.spacing.x = unit(0.5, 'cm'),
    legend.title.align=0.5)
```


```{r}
# 
# L = c()
# for(i in seq(20,200,by=20) ){
#   if (i < max(mydf$Wind) + 20){
#     L = append(L,i)
#   }
# }
# 
# ggmap(map) +
# geom_segment(
#   data = mydf,
#   aes(x = Lon1, y = Lat1, xend = Lon2, yend = Lat2, color=Wind),  
#   size = 6, 
#   alpha = 0.8,
#   lineend = "round")+
# geom_point(
#   data = mydf1, 
#   aes(x = Lon1, y = Lat1), alpha=0.35,size = 1.5,) +
# geom_point(
#   data = mydf2, 
#   aes(x = Lon1, y = Lat1), alpha=1,size = 3,) +
# scale_colour_gradientn(
#   name = "Wind Speed (mph)", 
#   colours = col, 
#   limits = c(20,round_any(max(mydf$Wind), 20, f = ceiling)), 
#   breaks = L, 
#   labels=L,
#   oob = scales::squish) +
# labs(x = "Longitude", y="Latitude")+
# THEME +
# guides(colour = guide_colorbar(title.position = "top"))

```


```{r}
# L = c()
# for(i in seq(900,1020,by=20) ){
#   L = append(L,i)
# }
# 
# C = 'Pressure'
# 
# ggmap(map) +
# geom_segment(data = mydf, aes_string(x = 'Lon1', y = 'Lat1', xend = 'Lon2', yend = 'Lat2', color=C), size = 6, alpha = 0.8, lineend = "round")+
# geom_point(data = mydf1, aes(x = Lon1, y = Lat1), alpha=0.35,size = 1.5,) +
# geom_point(data = mydf2, aes(x = Lon1, y = Lat1), alpha=1,size = 3,) +
# scale_colour_gradientn(name = "Pressure", colours = col, limits = c(900,1020), breaks = L, labels=L, oob = scales::squish) +
# labs(x = "Longitude", y="Latitude")+
# THEME +
# guides(colour = guide_colorbar(title.position = "top"))
```

```{r}
create_map <- function( column ) {
  L = c()
  for(i in seq(900,1020,by=20) ){
    L = append(L,i)
  }
  
  ggmap(map) +
  geom_segment(data = mydf, aes_string(x = 'Lon1', y = 'Lat1', xend = 'Lon2', yend = 'Lat2', color=column), size = 7, alpha = 1, lineend = "round")+
  geom_point(data = mydf1, aes(x = Lon1, y = Lat1), alpha=0.35,size = 2,) +
  geom_point(data = mydf2, aes(x = Lon1, y = Lat1), alpha=1,size = 3,) +
  scale_colour_gradientn(name = column, colours = col, limits = c(900,1020), breaks = L, labels=L, oob = scales::squish) +
  labs(x = "Longitude", y="Latitude")+
  THEME +
  guides(colour = guide_colorbar(title.position = "top"))
}

create_map('Pressure',900,1020,20)
create_map('Wind',20,160,20)
create_map('Accel',-4,4,1)
```

